version: '3'

services:
  tt_backend:
    image: tt_backend
    build: 
      context: ./tt-backend/tt-backend
    container_name: tt-backend
    ports:
      - "5201:5201"
    depends_on:
      - tt-db
    networks:
      - tt-network

  tt-frontend:
    container_name: tt-frontend
    image: tt_frontend
    build: 
      context: ./tt-frontend
    ports:
      - "3000:80"
    networks:
      - tt-network
    depends_on:
      - tt_backend
    environment:      
      BACKEND_URL: 'http://tt_backend:5201'

  tt-db:
    container_name: tt-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TechTreasure
    ports:
      - "5433:5432"
    expose:
      - 5433
      - 5432
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - tt-network

volumes:
  app_data:

networks:
  tt-network:
    driver: bridge

    